CREATE TABLE IF NOT EXISTS partnering_opportunity(
    meta_organization TEXT NOT NULL,
    meta_category TEXT NOT NULL,
    meta_collected_date TEXT NOT NULL,
    meta_base_url TEXT NOT NULL,
    title TEXT NOT NULL,
    publish_date TEXT,
    country TEXT,
    type TEXT,
    pod_reference TEXT,
    summary TEXT NOT NULL,
    description TEXT NOT NULL,
    advantages TEXT,
    stage_of_development TEXT,
    development_comments TEXT,
    ipr_status TEXT,
    profile_origin TEXT,
    technology_keywords TEXT,
    market_keywords TEXT,
    nace_keywords TEXT,
    partner_sought_role TEXT,
    partner_sought_size TEXT,
    partnership_type_considered TEXT,
    client_type TEXT,
    client_year_est TEXT,
    client_transnational_coop TEXT,
    client_comments TEXT,
    client_languages TEXT,
    client_country TEXT,
    sector_group TEXT
);
