# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='session',
        ),
        migrations.AddField(
            model_name='query',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
