# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-18 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171117_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
