# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_query_query_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Contact'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sector',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
