# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:00
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171121_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
