# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_content_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
