# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_content_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='publication',
            field=models.BooleanField(default=True),
        ),
    ]
