# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_content_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='year',
            field=models.IntegerField(blank=True, default=2017, null=True),
        ),
    ]
