# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171125_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='content',
            name='cost_curr',
        ),
        migrations.RemoveField(
            model_name='content',
            name='partnering_role',
        ),
        migrations.RemoveField(
            model_name='content',
            name='seeking_support',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tech_specifications',
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
