# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171125_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
