CREATE TABLE IF NOT EXISTS technology_request(
    meta_organization TEXT NOT NULL,
    meta_category TEXT NOT NULL,
    meta_collected_date TEXT NOT NULL,
    meta_base_url TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    sector TEXT,
    country TEXT,
    keywords TEXT,
    transfer_terms TEXT,
    studies TEXT,
    project_type TEXT,
    estimated_cost TEXT,
    target_cost TEXT,
    target_countries TEXT,
    partner_assistance TEXT,
    additional_info TEXT,
    contact_person TEXT,
    contact_address TEXT,
    contact_city TEXT,
    contact_country TEXT,
    contact_zip TEXT
);